#!/usr/bin/env python3
"""Download coding datasets for Research Corpus v2.

CodeSearchNet only - public, no auth required.
Stores as separate JSONL files. Does not rebuild FineWeb/Wikipedia.
"""

import os, sys, json, time, random, hashlib, re
from pathlib import Path
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def download_csn(target_per_lang, output_dir, rng, report):
    """Download CodeSearchNet across multiple languages."""
    from datasets import load_dataset
    from tqdm import tqdm

    langs = ["python", "java", "javascript", "go", "ruby", "php"]
    all_docs = []
    per_lang = max(1, target_per_lang // len(langs))

    for lang in langs:
        print(f"\n  Downloading {lang}...")
        start = time.time()
        try:
            ds = load_dataset(
                "code-search-net/code_search_net",
                name=lang,
                split="train",
                streaming=True,
            )
            docs = []
            seen_hashes = set()
            pbar = tqdm(total=per_lang, desc=f"    {lang}", unit="doc")
            for ex in ds:
                code = ex.get("func_code_string", "")
                docstring = ex.get("func_documentation_string", "")
                if not code or len(code.strip()) < 50:
                    continue
                # Remove minified code
                lines = code.split("\n")
                avg_line_len = sum(len(l) for l in lines) / max(len(lines), 1)
                if avg_line_len > 200:
                    continue
                # Remove auto-generated
                if any(kw in code.lower() for kw in ["auto-generated", "autogenerated", "do not edit", "generated by"]):
                    continue
                # Exact dedup
                h = hashlib.md5(code.encode()).hexdigest()
                if h in seen_hashes:
                    continue
                seen_hashes.add(h)
                docs.append({
                    "text": code,
                    "docstring": docstring,
                    "language": lang,
                    "repo": ex.get("repository_name", ""),
                    "func_name": ex.get("func_name", ""),
                    "source": "codesearchnet",
                })
                pbar.update(1)
                if len(docs) >= per_lang:
                    break
            pbar.close()
            elapsed = time.time() - start
            report.append({
                "dataset": f"codesearchnet_{lang}",
                "status": "ok",
                "documents": len(docs),
                "time_seconds": round(elapsed, 2),
                "failure_reason": "",
                "languages": lang,
            })
            all_docs.extend(docs)
            print(f"    {lang}: {len(docs):,} docs ({elapsed:.1f}s)")
        except Exception as e:
            elapsed = time.time() - start
            report.append({
                "dataset": f"codesearchnet_{lang}",
                "status": "failed",
                "documents": 0,
                "time_seconds": round(elapsed, 2),
                "failure_reason": str(e),
                "languages": lang,
            })
            print(f"    {lang} FAILED: {e}")

    # Save per-language files
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Group by language
    by_lang = {}
    for doc in all_docs:
        lang = doc.get("language", "unknown")
        by_lang.setdefault(lang, []).append(doc)

    for lang, docs in by_lang.items():
        fpath = output_dir / f"codesearchnet_{lang}.jsonl"
        with open(fpath, "w", encoding="utf-8") as f:
            for doc in docs:
                f.write(json.dumps(doc, ensure_ascii=False) + "\n")
        print(f"  Saved: {fpath} ({len(docs):,} docs)")

    # Merged file
    merged_path = output_dir / "codesearchnet.jsonl"
    with open(merged_path, "w", encoding="utf-8") as f:
        for doc in all_docs:
            f.write(json.dumps(doc, ensure_ascii=False) + "\n")
    print(f"  Saved: {merged_path} ({len(all_docs):,} docs)")

    return all_docs


def main():
    output_dir = Path("datasets/research_v2/coding")
    output_dir.mkdir(parents=True, exist_ok=True)

    target_total = 40000
    rng = random.Random(42)
    report = []

    print("=" * 60)
    print("CODING DATASET DOWNLOAD")
    print("=" * 60)

    all_coding = download_csn(target_total, output_dir, rng, report)

    # Summary
    total_coding = len(all_coding)
    total_chars = sum(len(d.get("text", "")) for d in all_coding)

    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")
    print(f"  Total docs: {total_coding:,}")
    print(f"  Total chars: {total_chars:,}")
    print(f"  Languages: {Counter(d.get('language','') for d in all_coding)}")

    # Save report
    report_path = output_dir / "coding_report.json"
    with open(report_path, "w") as f:
        json.dump({
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total_documents": total_coding,
            "total_chars": total_chars,
            "estimated_tokens": total_chars // 4,
            "datasets": report,
        }, f, indent=2)
    print(f"\n  Report: {report_path}")

    # Update main corpus: merge with existing FineWeb + Wikipedia
    main_corpus = Path("datasets/research_v2/corpus.jsonl")
    if main_corpus.exists():
        print(f"\n  Merging with existing corpus ({main_corpus})...")
        existing = []
        with open(main_corpus, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    existing.append(json.loads(line))
        print(f"  Existing: {len(existing):,} docs")

        # Add coding docs
        for doc in all_coding:
            existing.append(doc)
        print(f"  Total after merge: {len(existing):,}")

        # Shuffle and save
        rng.shuffle(existing)
        with open(main_corpus, "w", encoding="utf-8") as f:
            for doc in existing:
                f.write(json.dumps(doc, ensure_ascii=False) + "\n")

        # Update metadata
        total_chars = sum(len(d.get("text", "")) for d in existing)
        total_words = sum(len(d.get("text", "").split()) for d in existing)

        sources = {}
        for d in existing:
            src = d.get("source", d.get("language", "unknown"))
            sources[src] = sources.get(src, 0) + 1

        metadata = {
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total_documents": len(existing),
            "total_chars": total_chars,
            "total_words": total_words,
            "estimated_tokens": total_chars // 4,
            "avg_doc_len_chars": round(total_chars / max(len(existing), 1)),
            "avg_doc_len_words": round(total_words / max(len(existing), 1)),
            "sources": sources,
            "seed": 42,
            "corpus_version": "v2",
        }
        with open("datasets/research_v2/metadata.json", "w") as f:
            json.dump(metadata, f, indent=2)
        print(f"  Updated metadata.json")
    else:
        print(f"\n  No existing corpus found. Creating new one.")
        with open(main_corpus, "w", encoding="utf-8") as f:
            for doc in all_coding:
                f.write(json.dumps(doc, ensure_ascii=False) + "\n")

    print(f"\n{'='*60}")
    print("DONE")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
